import 'package:flutter/foundation.dart';
import 'package:foodre/Model/ExtendedIngredients.dart';

class FoodInformation {
  final String foodTitle;
  final String foodImageUrl;
  final int mints;
  final List<ExtendedIngredients> extendedIngredients;


  FoodInformation(
      {this.foodTitle, this.foodImageUrl, this.mints, this.extendedIngredients});


  factory FoodInformation.fromJson(Map<String, dynamic> parsedJson) {
    var list = parsedJson['extendedIngredients'] as List;

    List<ExtendedIngredients> imagesList = list.map((i) => ExtendedIngredients.fromJson(i)).toList();


    return FoodInformation(
        foodTitle: parsedJson['title'],
        foodImageUrl: parsedJson['image'],
        mints: parsedJson['readyInMinutes'],
        extendedIngredients: imagesList
    );
  }
}

//import 'ExtendedIngredients.dart';
//
//class Autogenerated {
//  List<ExtendedIngredients> extendedIngredients;
//  String title;
//  int readyInMinutes;
//  String image;
//
//  Autogenerated({
//    this.extendedIngredients,
//    this.title,
//    this.readyInMinutes,
//    this.image,
//  });
//
//  Autogenerated.fromJson(Map<String, dynamic> json) {
//    if (json['extendedIngredients'] != null) {
//      extendedIngredients = new List<ExtendedIngredients>();
//      json['extendedIngredients'].forEach((v) {
//        extendedIngredients.add(new ExtendedIngredients.fromJson(v));
//      });
//    }
//    title = json['title'];
//    readyInMinutes = json['readyInMinutes'];
//    image = json['image'];
//  }
//}
//
//class ExtendedIngredients {
//  int id;
//  String aisle;
//  String image;
//  String consistency;
//  String name;
//  String original;
//  String originalString;
//  String originalName;
//  double amount;
//  String unit;
//  List<String> meta;
//  List<String> metaInformation;
//
//  ExtendedIngredients({
//    this.id,
//    this.aisle,
//    this.image,
//    this.consistency,
//    this.name,
//    this.original,
//    this.originalString,
//    this.originalName,
//    this.amount,
//    this.unit,
//    this.meta,
//    this.metaInformation,
//  });
//
//  ExtendedIngredients.fromJson(Map<String, dynamic> json) {
//    id = json['id'];
//    aisle = json['aisle'];
//    image = json['image'];
//    consistency = json['consistency'];
//    name = json['name'];
//    original = json['original'];
//    originalString = json['originalString'];
//    originalName = json['originalName'];
//    amount = json['amount'];
//    unit = json['unit'];
//    meta = json['meta'].cast<String>();
//    metaInformation = json['metaInformation'].cast<String>();
//  }
//}
